/**
 * @swagger
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: ID de l'utilisateur
        lastName:
          type: string
          description: Nom de famille de l'utilisateur
        firstName:
          type: string
          description: Prénom de l'utilisateur
        email:
          type: string
          description: Adresse e-mail de l'utilisateur
        phone:
          type: string
          description: Numéro de téléphone de l'utilisateur
        nationality:
          type: string
          description: Nationalité de l'utilisateur
        permission:
          type: string
          description: Niveau d'autorisation de l'utilisateur
        password:
          type: string
          description: Mot de passe de l'utilisateur
        bookings:
          type: array
          items:
            $ref: '#/components/schemas/Booking'

    Article:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: ID de l'article
        title:
          type: string
          description: Titre de l'article
        description:
          type: string
          description: Description de l'article
        content:
          type: string
          description: Contenu de l'article
        date_publish:
          type: string
          format: date-time
          description: Date de publication de l'article
        date_update:
          type: string
          format: date-time
          description: Date de mise à jour de l'article
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageArticle'
        categorie:
          $ref: '#/components/schemas/CategorieArticle'
          
    ImageArticle:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: ID de l'image de l'article
        title:
          type: string
          description: Titre de l'image de l'article
        description:
          type: string
          description: Description de l'image de l'article
        urlStorage:
          type: string
          description: URL de stockage de l'image de l'article
        article:
          $ref: '#/components/schemas/Article'
          
    CategorieArticle:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: ID de la catégorie d'article
        title:
          type: string
          description: Titre de la catégorie d'article
        description:
          type: string
          description: Description de la catégorie d'article
        articles:
          type: array
          items:
            $ref: '#/components/schemas/Article'
            **/
           /**
 * @swagger
 * components:
 *   schemas:
 *     Room:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *         name:
 *           type: string
 *         description:
 *           type: string
 *         personNumberPerRoom:
 *           type: integer
 *         price:
 *           type: number
 *         bed:
 *           type: integer
 *         Booking:
 *           type: array
 *           items:
 *             $ref: '#/components/schemas/Booking'
 *         ImageRoom:
 *           type: array
 *           items:
 *             $ref: '#/components/schemas/ImageRoom'
 */

  
  /**
   * @swagger
   * components:
   *   schemas:
   *     ImageRoom:
   *       type: object
   *       properties:
   *         id:
   *           type: integer
   *         title:
   *           type: string
   *         description:
   *           type: string
   *         urlStorage:
   *           type: string
   *         room:
   *           $ref: '#/components/schemas/Room'
   */
  
  /**
   * @swagger
   * components:
   *   schemas:
   *     Booking:
   *       type: object
   *       properties:
   *         id:
   *           type: integer
   *         uuid:
   *           type: string
   *         phone:
   *           type: string
   *         email:
   *           type: string
   *         dateCheckIn:
   *           type: string
   *           format: date-time
   *         dateCheckOut:
   *           type: string
   *           format: date-time
   *         duration:
   *           type: integer
   *         personNumber:
   *           type: integer
   *         comment:
   *           type: string
   *         user:
   *           $ref: '#/components/schemas/User'
   *         room:
   *           $ref: '#/components/schemas/Room'
   *         hasPaid:
   *           type: boolean
   *         price:
   *           type: number
   *         stripePaymentIntent:
   *           type: string
   *         createdOn:
   *           type: string
   *           format: date-time
   *         updatedOn:
   *           type: string
   *           format: date-time
   *         paymentDate:
   *           type: string
   *           format: date-time
   */